---
- name: Configure Access Layer
  hosts: access
  gather_facts: false
  connection: network_cli
  tasks:
  
    - name: Create VLAN
      ios_vlan:
         vlan_id: "{{ item.id }}"
         name: "{{ item.name }}"
         state: present
      with_items: "{{ vlans }}"
      tags: access_vlans 

    - name: Configure L2 Interfaces - Trunk
      ios_l2_interface:
         name: "{{ item.name }}"
         mode: "{{ item.mode }}"
         trunk_allowed_vlans: "{{ item.trunk_allowed_vlans }}"
         state: "{{ item.state }}"
      with_items: "{{ interfaces_l2 }}"
      when: item.mode == "trunk"
      tags: access_l2_int

    - name: Configure L2 Interfaces - Access
      ios_l2_interface:
         name: "{{ item.name }}"
         mode: "{{ item.mode }}"
         access_vlan: "{{ item.access_vlan }}"
         state: "{{ item.state }}"
      with_items: "{{ interfaces_l2 }}"
      when: item.mode == "access"
      tags: access_l2_int
           
- name: Configure Aggregation Layer
  hosts: aggregation
  gather_facts: false
  connection: network_cli
  tasks:

    - name: Create VLAN
      nxos_vlan:
         vlan_id: "{{ item.id }}"
         name: "{{ item.name }}"
         state: present
      with_items: "{{ vlans }}"
      tags: aggr_vlans

    - name: Configure L2 Interfaces - Trunk
      nxos_l2_interface:
         name: "{{ item.name }}"
         mode: "{{ item.mode }}"
         trunk_allowed_vlans: "{{ item.trunk_allowed_vlans }}"
         state: "{{ item.state }}"
      with_items: "{{ interfaces_l2 }}"
      when: item.mode == "trunk"
      tags: aggr_l2_int

    - name: Enable Features
      nxos_feature:
         feature: interface-vlan
         state: enabled
      tags: aggr_features
   
    - name: Initialize L3 Interfaces
      nxos_interface:
        name: "{{ item.name }}" 
        state: present
      with_items: "{{ interfaces_l3 }}"
      tags: aggr_l3_svi

    - name: Configure L3 Interfaces
      nxos_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        state: present
      with_items: "{{ interfaces_l3 }}"
      tags: aggr_l3_svi

